# Generated by Django 4.1.2 on 2022-11-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_assets_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='url_to_artstation',
        ),
        migrations.AddField(
            model_name='assets',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='assets',
            name='name_of_work',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assets')),
            ],
            options={
                'verbose_name': 'Работa_полн.',
                'verbose_name_plural': 'Работы_полн.',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_image_path', models.ImageField(unique=True, upload_to='portfolio/static/portfolio/img/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assets')),
            ],
            options={
                'verbose_name': 'Рендер',
                'verbose_name_plural': 'Рендеры',
                'ordering': ['id'],
            },
        ),
    ]
