# Generated by Django 4.1.2 on 2023-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_assets_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='bdf',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='blender',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='photoshop',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='zbrush',
            field=models.BooleanField(null=True),
        ),
    ]
